spring:
  application:
    name: telegramBot
  sql:
    init:
      mode: never
  datasource:
    username: hookah
    password: hookah
    url: jdbc:postgresql://localhost:5438/hookah-db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true